
PROJECT_NAME = tilescale
BUILD_DIR = build
SOURCE_DIR = src
HEADER_DIR = include

#------------------------------------------------------------------------------
#									SETUP
#------------------------------------------------------------------------------

CC = gcc
CFLAGS = -std=c11 -g
LDFLAGS = -g
LIBS = libpng
STATIC_LIBS = 
INCLUDES = -I$(HEADER_DIR)
ifdef LIBS
LDLIBS = $(shell pkg-config -libs $(LIBS))
INCLUDES += $(shell pkg-config -cflags $(LIBS))
endif
ifdef STATIC_LIBS
LDLIBS += -Wl,-Bstatic $(shell pkg-config -libs $(STATIC_LIBS)) -Wl,-Bdynamic
INCLUDES += $(shell pkg-config -cflags $(STATIC_LIBS))
endif

SRC = $(shell find $(SOURCE_DIR)/ -type f -name '*.c') main.c
NOM = $(basename $(patsubst $(SOURCE_DIR)/%,%,$(SRC)))
OBJ = $(addprefix $(BUILD_DIR)/,$(addsuffix .o, $(NOM)))
DEP = $(addprefix $(BUILD_DIR)/,$(addsuffix .d, $(NOM)))

VPATH += $(SRC)

#------------------------------------------------------------------------------
#								MAIN BUILD RULES
#------------------------------------------------------------------------------

# Main rule 
all: init build  

# General build
build: $(PROJECT_NAME)

# Build all the .o files in src dir
$(BUILD_DIR)/%.o: $(SOURCE_DIR)/%.c Makefile
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -MMD -MP -c $< $(INCLUDES) -o $@

# Build all the .o files in base dir
$(BUILD_DIR)/%.o: %.c Makefile
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -MMD -MP -c $< $(INCLUDES) -o $@

# Main program
$(PROJECT_NAME): $(OBJ)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@

# Helloworld
kyoutest: 	$(BUILD_DIR)/helloworld.o
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@

# Dependancies generated by GCC (for headers)
-include $(DEP)


#------------------------------------------------------------------------------
#								SILLY RULES
#------------------------------------------------------------------------------

always: SUSSYBAKA
	@echo "Aloha :3"

SUSSYBAKA:


#------------------------------------------------------------------------------
#								UTILITIES
#------------------------------------------------------------------------------

rebuild: clean build

init: clear
	mkdir -p $(BUILD_DIR)

test:
	@echo CC: $(CC)
	@echo CFLAGS: $(CFLAGS)
	@echo LDFLAGS: $(LDFLAGS)
	@echo LIBS: $(LIBS)
	@echo LDLIBS: $(LDLIBS)
	@echo SOURCE_DIR: $(SOURCE_DIR)
	@echo HEADER_DIR: $(HEADER_DIR)
	@echo OBJ: $(OBJ)
	@echo SRC: $(SRC)
	@echo DEP: $(DEP)
	@echo INCLUDES: $(INCLUDES)

run: $(PROJECT_NAME)
	./$(PROJECT_NAME) sample_in.png out.png

clean:
	@rm -if $(OBJ) $(DEP) $(RES) $(RES_DEP)
#	@rm -rif *.o *.gch
#	@rm -rif $(BUILD_DIR)/*.o $(BUILD_DIR)/*.gch

clear: clean
	@rm -if $(PROJECT_NAME) $(RES_INC)


.PHONY: always init SUSSYBAKA test clear clean run